Importing libraries that we will need to the analysis:

In [1]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

Reading and visualization of the training and test dataset:

In [2]:
dataset_train = pd.read_csv('./j0001_train.csv')
dataset_test = pd.read_csv('./j0001_X_test.csv')

In [3]:
dataset_train.head()

feature1  feature2  feature3  feature4      target
0  0.885598 -0.058136 -0.502394 -0.072880    4.999557
1  1.391696  0.350938  0.311445 -0.780685   56.613234
2 -0.599735 -0.072272  1.541158 -0.384914   43.374539
3  1.108150  1.924439 -0.068485  1.985521   50.226308
4 -0.724598 -1.485027 -1.755203 -0.254649 -107.187888

In [4]:
dataset_test.head()

feature1  feature2  feature3  feature4
0  0.597102  1.877031  0.304122 -2.236589
1 -0.076417  0.629597 -0.768331 -0.604651
2  0.324997 -0.547428  0.209863 -1.202035
3 -0.200883  0.065955  0.933417  0.104939
4 -1.251144 -1.491532  0.411994  1.943790

As we could see, we have 4 predictor variables, so we need to apply multiple linear regression

To take a first glance about the statistical details of the dataset, I use the function "describe"

In [5]:
dataset_train.describe()

feature1     feature2     feature3     feature4       target
count  2100.000000  2100.000000  2100.000000  2100.000000  2100.000000
mean     -0.027414     0.001468    -0.013670    -0.016315    -1.325515
std       0.986569     0.993519     1.003757     1.008821    49.995929
min      -3.193735    -3.986392    -2.987483    -3.254383  -153.822702
25%      -0.705434    -0.637161    -0.704697    -0.714512   -36.070943
50%      -0.030567     0.030049    -0.022917    -0.021288    -1.646837
75%       0.670686     0.665407     0.673575     0.693128    32.707651
max       3.277599     3.190221     3.207883     3.281604   170.703958

I divide the model between predictor variables and target and train the model with the library Scikit-Learn:

In [6]:
X_train = np.array(dataset_train[['feature1', 'feature2', 'feature3', 'feature4']])
y_train = dataset_train['target'].values

In [7]:
# We train the model with 4 variables
regression_model = linear_model.LinearRegression()
regression_model = regression_model.fit(X_train, y_train)

I predict the values to compare the model:

In [8]:
y_prediction = regression_model.predict(X_train)
y_prediction

array([  4.99955743,  56.61323375,  43.37453898, ...,  54.71881402,
        34.35076859, -72.7152765 ])

Checking the test error with the mean squared error, the variance score and the regression coefficients of our model:

In [9]:
print('Regression coefficients: \n', regression_model.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_train, y_prediction))
print('Variance score (with 1.0 the best possible value): %.2f' % r2_score(y_train, y_prediction))
print('Intercept (value at which the fitted line crosses the y-axis):',regression_model.intercept_)

Regression coefficients: 
 [2.90140088e+01 1.08134628e+01 3.99418878e+01 6.32571199e-15]
Mean squared error: 0.00
Variance score (with 1.0 the best possible value): 1.00
Intercept (value at which the fitted line crosses the y-axis): -2.220446049250313e-16


What we can observe with regression coefficients obtained is that the 4th column is not relevant to the model

Now, I will be predict with the model out test dataset and print the first 10 results:

In [10]:
X_test = dataset_test
y_test = regression_model.predict(X_test)

In [11]:
y_test[0:10]

array([ 49.76877045, -26.0976422 ,  11.89220071,  32.16721412,
       -35.973501  , -66.6045499 ,  -1.15629449, -63.96369663,
       -21.14764534,  84.21462532])

In [12]:
pd.DataFrame(y_test).to_csv('./results.csv', header='results', index=False)